<?php


namespace SilverStripe\Snapshots\Handler\Elemental;

use SilverStripe\EventDispatcher\Event\EventContextInterface;
use SilverStripe\Snapshots\Handler\Form\SaveHandler;
use SilverStripe\Snapshots\Snapshot;

class ElementalEditorHandler extends SaveHandler
{
    protected function createSnapshot(EventContextInterface $context): ?Snapshot
    {
        return parent::createSnapshot($context); // TODO: Change the autogenerated stub
    }
}
